hydra:
  output_subdir: null
  run:
    dir: ./

seed: 1
agent_type: "dqn"
use_history: False
target_steps: 10
reward_window: 10
dqn_agent:
  gamma: 0.999
  eps_final: 0
  eps_init: 1
  eps_decay: 500
  buffer_size: 10000
  hidden_size: 40
  num_layers: 0
  batch_norm: False
  model_type: "mlp"
  batch_size: 128
  history_len: 2
a2c_agent:
  gamma: 0.999
  eps_final: 0
  eps_init: 1
  eps_decay: 500
  buffer_size: 10000
  hidden_size: 40
  num_layers: 0
  batch_norm: False
  model_type: "mlp"
  batch_size: 128
  history_len: 2