hydra:
  output_subdir: null
  run:
    dir: /network/scratch/j/juan.duque/hydra/

seed: 1
agent_type: "dqn"
use_history: False
target_steps: 10
reward_window: 10
is_pc: False
base_agent:
  gamma: 0.999
  buffer_size: 100000
  hidden_size: 64
  num_layers: 0
  batch_norm: False
  model_type: "mlp"
  actor_type: "lstm"
  use_actions: False
  batch_size: 128
  history_len: 2
  temperature: 1
  opt_type: "sgd"
dqn_agent:
  gamma: 0.999
  eps_final: 0
  eps_init: 1
  eps_decay: 500
a2c_agent:
  is_pc: False
nash_ac_agent:
  lstm_out: 20
  temperature: 1
rf_nash_ac_agent:
  policy_hist_len: 8
  lstm_out: 20
  temperature: 1
  is_p_pc: False
sgd:
  lr: 0.0001
  momentum: 0.9
optim:
  lr: 0.001
  adam_lr: 0.0001
  momentum: 0.9